// Keyboard Layout Definitions
// ===========================
//
// KEY SYNTAX:
// -----------
// Simple key:     "a"                    - Types "a", shifts to "A" automatically
// With shift:     { "key": "ü", "shift": "Ü" }  - Explicit shift character
// With menu:      { "key": "e", "menu": "FrE" } - Long-press shows overlay "FrE"
// Display shift:  { "key": "ㅂ", "shift": "ㅃ", "display": true } - Shows shifted char on key
//
// SPECIAL KEYS:
// -------------
// "Backspace"      - Standard backspace (kbdHB class)
// "BackspaceSmall" - Smaller backspace for wide keyboards (kbdHBS class)
// "Enter"          - Standard enter key (kbdHBE class)
// "EnterBottom"    - Enter in bottom row (kbdD class, for Hungarian)
// "Shift"          - Shift with icon (kShift class)
// "ShiftLabel"     - Shift with "Shift" text label (for Hungarian)
// "Space"          - Spacebar
// "Close"          - Close keyboard button
// "Url"            - URL button
// "&123"           - Toggle numbers/symbols mode
// "Settings"       - Settings menu button
// "_spacer"        - Empty cell for row alignment
//
// SPECIAL SYNTAX:
// ---------------
// "?|@"  - Email input toggle: shows "?" normally, "@" for email inputs
//          First char = shown normally (kbHideEmailInput class)
//          Second char = shown for email inputs (kbEmailInput class)
//
// LAYOUT STRUCTURE:
// -----------------
// {
//   "name": "Display Name",
//   "labels": { "Backspace": "Custom Label" },  // Optional custom key labels
//   "rows": [ [...], [...], [...] ],            // Main keyboard rows (usually 3)
//   "bottomRow": ["&123", "Settings", ...],     // Optional custom bottom row
//   "overlays": { "MenuId": [...] }             // Optional long-press menus
// }
//
// Default bottom row (if not specified): ["&123", "Settings", "Space", "Close"]

const layouts = {
  en: {
    name: "English (QWERTY)",
    rows: [
      ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "Backspace"],
      ["_spacer", "a", "s", "d", "f", "g", "h", "j", "k", "l", "'", "Enter"],
      [
        "Shift",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
  },

  fr: {
    name: "French (AZERTY)",
    rows: [
      [
        { key: "a", menu: "FrA" },
        "z",
        { key: "e", menu: "FrE" },
        "r",
        "t",
        { key: "y", menu: "FrY" },
        { key: "u", menu: "FrU" },
        { key: "i", menu: "FrI" },
        { key: "o", menu: "FrO" },
        "p",
        "Backspace",
      ],
      ["_spacer", "q", "s", "d", "f", "g", "h", "j", "k", "l", "m", "Enter"],
      [
        "Shift",
        ",",
        "w",
        "x",
        { key: "c", menu: "FrC" },
        "v",
        "b",
        { key: "n", menu: "FrN" },
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
    overlays: {
      FrA: [
        "a",
        { key: "à", shift: "À" },
        { key: "â", shift: "Â" },
        { key: "æ", shift: "Æ" },
        { key: "ä", shift: "Ä" },
        { key: "ã", shift: "Ã" },
      ],
      FrC: ["c", { key: "ç", shift: "Ç" }],
      FrE: [
        "e",
        { key: "é", shift: "É" },
        { key: "è", shift: "È" },
        { key: "ê", shift: "Ê" },
        { key: "ë", shift: "Ë" },
      ],
      FrI: [
        "i",
        { key: "í", shift: "Í" },
        { key: "ì", shift: "Ì" },
        { key: "î", shift: "Î" },
        { key: "ï", shift: "Ï" },
      ],
      FrN: ["n", { key: "ñ", shift: "Ñ" }],
      FrO: [
        "o",
        { key: "ó", shift: "Ó" },
        { key: "ò", shift: "Ò" },
        { key: "ô", shift: "Ô" },
        { key: "ö", shift: "Ö" },
        { key: "õ", shift: "Õ" },
        { key: "ø", shift: "Ø" },
      ],
      FrU: [
        "u",
        { key: "ú", shift: "Ú" },
        { key: "ù", shift: "Ù" },
        { key: "û", shift: "Û" },
        { key: "ü", shift: "Ü" },
      ],
      FrY: ["y", { key: "ý", shift: "Ý" }, { key: "ÿ", shift: "Ÿ" }],
    },
  },

  de: {
    name: "German (QWERTZ)",
    rows: [
      [
        "q",
        "w",
        { key: "e", menu: "DeE" },
        "r",
        "t",
        "z",
        "u",
        "i",
        { key: "o", menu: "DeO" },
        { key: "p", menu: "DeP" },
        { key: "ü", shift: "Ü" },
        "Backspace",
      ],
      [
        "_spacer",
        { key: "a", menu: "DeA" },
        "s",
        "d",
        "f",
        "g",
        { key: "h", menu: "DeH" },
        "j",
        "k",
        "l",
        { key: "ö", shift: "Ö" },
        { key: "ä", shift: "Ä" },
        "Enter",
      ],
      [
        "Shift",
        "y",
        "x",
        "c",
        "v",
        "b",
        "n",
        { key: "m", menu: "DeM" },
        ",",
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
    overlays: {
      DeM: ["m", { key: "µ", shift: "M" }],
      DeE: ["e", { key: "œ", shift: "Œ" }],
      DeO: ["o", { key: "ø", shift: "Ø" }],
      DeP: ["p", { key: "þ", shift: "Þ" }],
      DeA: ["a", { key: "æ", shift: "Æ" }],
      DeH: ["h", { key: "ß", shift: "ß" }],
    },
  },

  it: {
    name: "Italian (QWERTY)",
    rows: [
      [
        "q",
        "w",
        { key: "e", menu: "ItE" },
        "r",
        "t",
        "y",
        { key: "u", menu: "ItU" },
        { key: "i", menu: "ItI" },
        { key: "o", menu: "ItO" },
        "p",
        "Backspace",
      ],
      [
        "_spacer",
        { key: "a", menu: "ItA" },
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        "'",
        "Enter",
      ],
      [
        "Shift",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
    overlays: {
      ItA: [
        "a",
        { key: "à", shift: "À" },
        { key: "á", shift: "Á" },
        { key: "â", shift: "Â" },
        { key: "ä", shift: "Ä" },
      ],
      ItE: [
        "e",
        { key: "é", shift: "É" },
        { key: "è", shift: "È" },
        { key: "ë", shift: "Ë" },
        { key: "ê", shift: "Ê" },
      ],
      ItI: [
        "i",
        { key: "ì", shift: "Ì" },
        { key: "í", shift: "Í" },
        { key: "î", shift: "Î" },
        { key: "ï", shift: "Ï" },
      ],
      ItO: ["o", { key: "ò", shift: "Ò" }, { key: "ö", shift: "Ö" }],
      ItU: ["u", { key: "ù", shift: "Ù" }, { key: "ü", shift: "Ü" }],
    },
  },

  es: {
    name: "Spanish (QWERTY)",
    labels: { Backspace: "Borrar", Enter: "Intro" },
    rows: [
      ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "Backspace"],
      [
        "_spacer",
        "a",
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        { key: "ñ", shift: "Ñ" },
        { key: "ç", shift: "Ç" },
        "Enter",
      ],
      [
        "Shift",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
  },

  // Russian uses Cyrillic - each key needs explicit shift mapping
  ru: {
    name: "Russian (JCUKEN)",
    rows: [
      [
        { key: "й", shift: "Й" },
        { key: "ц", shift: "Ц" },
        { key: "у", shift: "У" },
        { key: "к", shift: "К" },
        { key: "е", shift: "Е" },
        { key: "н", shift: "Н" },
        { key: "г", shift: "Г" },
        { key: "ш", shift: "Ш" },
        { key: "щ", shift: "Щ" },
        { key: "з", shift: "З" },
        { key: "х", shift: "Х" },
        { key: "ъ", shift: "Ъ" },
        "BackspaceSmall",
      ],
      [
        "_spacer",
        { key: "ф", shift: "Ф" },
        { key: "ы", shift: "Ы" },
        { key: "в", shift: "В" },
        { key: "а", shift: "А" },
        { key: "п", shift: "П" },
        { key: "р", shift: "Р" },
        { key: "о", shift: "О" },
        { key: "л", shift: "Л" },
        { key: "д", shift: "Д" },
        { key: "ж", shift: "Ж" },
        { key: "э", shift: "Э" },
        "Enter",
      ],
      [
        "Shift",
        { key: "я", shift: "Я" },
        { key: "ч", shift: "Ч" },
        { key: "с", shift: "С" },
        { key: "м", shift: "М" },
        { key: "и", shift: "И" },
        { key: "т", shift: "Т" },
        { key: "ь", shift: "Ь" },
        { key: "б", shift: "Б" },
        { key: "ю", shift: "Ю" },
        "?|@",
        "Url",
        "Shift",
      ],
    ],
    // Custom bottom row with punctuation around spacebar
    bottomRow: ["&123", "Settings", ".", "Space", ",", "Close"],
  },

  // Korean uses Hangul Jamo - some keys have shift variants, some have long-press menus
  kr: {
    name: "Korean",
    rows: [
      [
        { key: "ㅂ", shift: "ㅃ", display: true },
        { key: "ㅈ", shift: "ㅉ", display: true },
        { key: "ㄷ", shift: "ㄸ", display: true },
        { key: "ㄱ", shift: "ㄲ", display: true },
        { key: "ㅅ", shift: "ㅆ", menu: "Kr1", display: true },
        "ㅛ",
        "ㅕ",
        "ㅑ",
        { key: "ㅐ", shift: "ㅒ", display: true },
        { key: "ㅔ", shift: "ㅖ", display: true },
        "Backspace",
      ],
      [
        "_spacer",
        "ㅁ",
        "ㄴ",
        "ㅇ",
        "ㄹ",
        { key: "ㅎ", menu: "Kr2" },
        "ㅗ",
        "ㅓ",
        "ㅏ",
        "ㅣ",
        "'",
        "Enter",
      ],
      [
        "Shift",
        "ㅋ",
        "ㅌ",
        "ㅊ",
        { key: "ㅍ", menu: "Kr3" },
        "ㅠ",
        "ㅜ",
        "ㅡ",
        ",",
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
    overlays: {
      Kr1: [
        { key: "ㅅ", shift: "ㅉ", display: true },
        { key: "쇼", shift: "쑈", display: true },
      ],
      Kr2: ["ㅎ", "호"],
      Kr3: ["ㅍ", "퓨"],
    },
  },

  // Hungarian has many special characters and a unique layout
  hu: {
    name: "Magyar (QWERTY)",
    labels: { Backspace: "Töröl", Shift: "Shift" },
    rows: [
      [
        "q",
        "w",
        "e",
        "r",
        "t",
        "z",
        "u",
        "i",
        "o",
        "p",
        { key: "ő", shift: "Ő" },
        { key: "ú", shift: "Ú" },
        "Backspace",
      ],
      [
        "_spacer",
        "a",
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        { key: "é", shift: "É" },
        { key: "á", shift: "Á" },
        { key: "ű", shift: "Ű" },
      ],
      // ShiftLabel = Shift key with text label instead of icon
      [
        "ShiftLabel",
        { key: "í", shift: "Í" },
        "y",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        { key: "ö", shift: "Ö" },
        { key: "ü", shift: "Ü" },
        { key: "ó", shift: "Ó" },
        ",",
        ".",
        "?",
      ],
    ],
    // Enter is in bottom row for Hungarian
    bottomRow: ["&123", "Settings", "Space", "Close", "EnterBottom"],
  },

  no: {
    name: "Norwegian (QWERTY)",
    rows: [
      [
        "q",
        "w",
        "e",
        "r",
        "t",
        "y",
        "u",
        "i",
        "o",
        "p",
        { key: "å", shift: "Å" },
        "Backspace",
      ],
      [
        "_spacer",
        "a",
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        { key: "ø", shift: "Ø" },
        { key: "æ", shift: "Æ" },
        "Enter",
      ],
      [
        "Shift",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
  },

  // Polish uses lowercase overlay IDs (Ple not PlE)
  pl: {
    name: "Polish (QWERTY)",
    rows: [
      [
        "q",
        "w",
        { key: "e", menu: "Ple" },
        "r",
        "t",
        "y",
        { key: "u", menu: "Plu" },
        "i",
        { key: "o", menu: "Plo" },
        "p",
        "Backspace",
      ],
      [
        "_spacer",
        { key: "a", menu: "Pla" },
        { key: "s", menu: "Pls" },
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        { key: "l", menu: "Pll" },
        "'",
        "Enter",
      ],
      [
        "Shift",
        { key: "z", menu: "Plz" },
        { key: "x", menu: "Plx" },
        { key: "c", menu: "Plc" },
        "v",
        "b",
        { key: "n", menu: "Pln" },
        "m",
        ",",
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
    overlays: {
      Ple: ["e", { key: "ę", shift: "Ę" }],
      Plu: ["u", "€"], // Euro sign, no shift variant
      Plo: ["o", { key: "ó", shift: "Ó" }],
      Pla: ["a", { key: "ą", shift: "Ą" }],
      Pls: ["s", { key: "ś", shift: "Ś" }],
      Pll: ["l", { key: "ł", shift: "Ł" }],
      Plz: ["z", { key: "ż", shift: "Ż" }],
      Plx: ["x", { key: "ź", shift: "Ź" }],
      Plc: ["c", { key: "ć", shift: "Ć" }],
      Pln: ["c", { key: "ń", shift: "Ń" }], // Note: first item is "c" in original HTML (likely a bug)
    },
  },

  sl: {
    name: "Slovenian (QWERTZ)",
    labels: { Backspace: "Back" },
    rows: [
      [
        "q",
        "w",
        "e",
        "r",
        "t",
        "z",
        "u",
        "i",
        "o",
        "p",
        { key: "š", shift: "Š" },
        { key: "đ", shift: "Đ" },
        { key: "ž", shift: "Ž" },
        "Backspace",
      ],
      [
        "_spacer",
        "a",
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        { key: "č", shift: "Č" },
        { key: "ć", shift: "Ć" },
        "Enter",
      ],
      [
        "Shift",
        "<",
        "y",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "-",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
  },

  sw: {
    name: "Swedish (QWERTY)",
    rows: [
      ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "å", "BackspaceSmall"],
      [
        "_spacer",
        "a",
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        "ö",
        "ä",
        "Enter",
      ],
      [
        "Shift",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
  },

  ta: {
    name: "Tamil 99",
    labels: { Backspace: "<---" },
    rows: [
      [
        { key: "ஆ", shift: "ஆ" },
        "ஈ",
        "ஊ",
        "ஐ",
        "ஏ",
        "ள",
        "ற",
        "ன",
        "ட",
        "ண",
        "ச",
        "ஞ",
        "Backspace",
      ],
      [
        "_spacer",
        "அ",
        "இ",
        "உ",
        "்",
        "எ",
        "க",
        "ப",
        "ம",
        "த",
        "ந",
        "ய",
        "Enter",
      ],
      [
        "Shift",
        "ஔ",
        "ஓ",
        "ஒ",
        "வ",
        "ங",
        "ல",
        "ர",
        ",",
        ".",
        "ழ",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
  },

  // Czech has an extra row of diacritical characters at the top
  cs: {
    name: "Czech (QWERTY)",
    rows: [
      // Extra row with Czech diacritical characters
      [
        { key: "ě", shift: "Ě" },
        { key: "š", shift: "Š" },
        { key: "č", shift: "Č" },
        { key: "ř", shift: "Ř" },
        { key: "ž", shift: "Ž" },
        { key: "ý", shift: "Ý" },
        "á",
        "í",
        "é",
        "ó",
        { key: "ů", shift: "Ů" },
        "ú",
        "ü",
        { key: "ď", shift: "Ď" },
        { key: "ť", shift: "Ť" },
        { key: "ň", shift: "Ň" },
      ],
      // Standard QWERTY row
      ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "Backspace"],
      ["_spacer", "a", "s", "d", "f", "g", "h", "j", "k", "l", "'", "Enter"],
      [
        "Shift",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "?|@",
        "Url",
        "Shift",
      ],
    ],
  },

  // Ukrainian - similar to Russian but with different letters (і, ї, є instead of ы, э, ъ)
  ua: {
    name: "Ukrainian (QWERTY)",
    rows: [
      [
        { key: "й", shift: "Й" },
        { key: "ц", shift: "Ц" },
        { key: "у", shift: "У" },
        { key: "к", shift: "К" },
        { key: "е", shift: "Е" },
        { key: "н", shift: "Н" },
        { key: "г", shift: "Г" },
        { key: "ш", shift: "Ш" },
        { key: "щ", shift: "Щ" },
        { key: "з", shift: "З" },
        { key: "х", shift: "Х" },
        { key: "ї", shift: "Ї" },
        "BackspaceSmall",
      ],
      [
        "_spacer",
        { key: "ф", shift: "Ф" },
        { key: "і", shift: "І" },
        { key: "в", shift: "В" },
        { key: "а", shift: "А" },
        { key: "п", shift: "П" },
        { key: "р", shift: "Р" },
        { key: "о", shift: "О" },
        { key: "л", shift: "Л" },
        { key: "д", shift: "Д" },
        { key: "ж", shift: "Ж" },
        { key: "є", shift: "Є" },
        "Enter",
      ],
      [
        "Shift",
        { key: "я", shift: "Я" },
        { key: "ч", shift: "Ч" },
        { key: "с", shift: "С" },
        { key: "м", shift: "М" },
        { key: "и", shift: "И" },
        { key: "т", shift: "Т" },
        { key: "ь", shift: "Ь" },
        { key: "б", shift: "Б" },
        { key: "ю", shift: "Ю" },
        "?|@",
        "Url",
        "Shift",
      ],
    ],
    bottomRow: ["&123", "Settings", ".", "Space", ",", "Close"],
  },
};

// Export for use by layoutRenderer.js
window.KEYBOARD_LAYOUTS = layouts;
